config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers:{
    sessions: "users/sessions",
    registrations: "users/registrations"
  }


  resources :offers do
    member do
      post 'postular' # Esto crea postular_offer_path
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.


  devise_scope :user do
    get "admin/login", to: "users/sessions#new", as: :new_admin_session
    get "admin/sign_up", to: "users/registrations#new", as: :new_admin_registration
  end




  namespace :admin do
    resources :users, only: [:new, :create]
  end

# Esto generará automáticamente las rutas RESTful para index, show, new, create, edit, update y destroy.
  resources :offers do
    post :request, on: :member
  end
    
    

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest





  # Defines the root path route ("/")
  root "offers#index"
end

app/views/shared/_navbar.html.erb
    <nav class="navbar navbar-expand-lg bg-light px-5">
        <div class="container-fluid">
            <%= link_to 'Postula', root_path, class: 'navbar-brand' %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <% if current_user && current_user.is_admin %>
                          <%= link_to 'Crear Oferta', new_offer_path, class: 'nav-link' %>
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <% if current_user&.is_admin? %>
                            <%= link_to 'Crear usuario', new_admin_user_path , class: 'nav-link' %>
                        <% end %>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <% if user_signed_in? %>                     
                                Hola <%= current_user.email %>
                        <% else %>
                            Conectate
                            <% end %>
                        </a>
                        <ul class="dropdown-menu shadow">
                            <% if user_signed_in? %>
                                <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                            <% else %>
                                <li>
                                <%= link_to 'Iniciar sesión',  new_user_session_path, class: 'dropdown-item'%>  
                                </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li> 
                                        <%= 
                                            if User.count == 0 
                                                link_to 'Registro',  new_user_registration_path, class: 'dropdown-item'
                                            else
                                                link_to ' Registro',  new_user_registration_path, class: 'dropdown-item nav-link disabled'
                                            end
                                        %>
                                    </li>
                            <% end %>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>  