config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers:{
    sessions: "users/sessions",
    registrations: "users/registrations"
  }


  resources :offers do
    member do
      post 'postular' # Esto crea postular_offer_path
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.


  devise_scope :user do
    get "admin/login", to: "users/sessions#new", as: :new_admin_session
    get "admin/sign_up", to: "users/registrations#new", as: :new_admin_registration
  end




  namespace :admin do
    resources :users, only: [:new, :create]
  end

# Esto generará automáticamente las rutas RESTful para index, show, new, create, edit, update y destroy.
  resources :offers do
    post :request, on: :member
  end
    
    

  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest





  # Defines the root path route ("/")
  root "offers#index"
end

app/models/offer.rb
# == Schema Information
#
# Table name: offers
#
#  id          :bigint           not null, primary key
#  title       :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Offer < ApplicationRecord

  has_many :requests
  has_many :users, through: :requests
  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy]




  def index
    @offers = Offer.all
    @is_admin = User.find_by(is_admin: true)
    @requests = Request.all
  end



  def show
    # No es necesario cargar todas las ofertas aquí, ya que @offer ya está definido en set_offer
    # solo se puede dejar vacío o agregar un comentario si es necesario
  end




  def postular
    @offer = Offer.find(params[:id])
    # Aquí va la lógica para el proceso de postulación
    # Ejemplo: Registrar al usuario actual para la oferta
    
    # if current_user.apply_to_offer(@offer) # Asume que existe un método `apply_to_offer`
    #   flash[:notice] = "Has postulado exitosamente a la oferta."
    # else
    #   flash[:alert] = "No se pudo completar la postulación."
    # end
    # redirect_to offers_path
    #***************************************
    # Aquí puedes implementar la lógica de postulación
    # Por ejemplo, podrías asociar al usuario actual con la oferta:
    current_user.offers << @offer

    redirect_to offers_path, notice: "Has postulado a la oferta exitosamente."
  end



  def requests
    @offer = Offer.find(params[:id])

    # Crear la solicitud si no existe
    if current_user.offers.exists?(@offer.id)
      redirect_to offers_path, alert: "Ya has solicitado esta oferta."
    else
      current_user.offers << @offer
      redirect_to offers_path, notice: "Has solicitado la oferta exitosamente."
      #desactivar boton
    end

  end



  def edit
  end




  def new
    @offer = Offer.new
  end




  def create
    @offer = Offer.new(offer_params)
    if @offer.save
      redirect_to offers_path, notice: 'La oferta fue creada exitosamente.'
    else
      render :new
    end
  end





  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: 'La oferta fue actualizada exitosamente.'
    else
      render :edit
    end
  end



  def destroy
    @offer.destroy
    redirect_to offers_path, notice: 'La oferta fue eliminada exitosamente.'
  end





  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def offer_params
    params.require(:offer).permit(:title, :description, :price)
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/edit.html.erb
<h1>Editar Oferta</h1>

<%= form_with(model: @offer, local: true) do |form| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibieron que esta oferta se guardara:</h2>

      <ul>
        <% @offer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="actions">
    <%= form.submit 'Actualizar Oferta' %>
  </div>
<% end %>

<%= link_to 'Volver', offers_path, class: 'btn btn-secondary' %>

app/views/offers/index.html.erb
<h4>Ofertas de Trabajo</h4>

<% i = 1 %>
<% if Offer.count != 0 %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Trabajo</th>
        <th scope="col">Descripcion</th>
        <% if current_user&.is_admin %>
          <th scope="col">Postulantes</th>  
        <% else %>
          <th scope="col">Postula</th>  
        <% end %>
      </tr>
    </thead>
    <tbody>
    
    <% @offers.each do |offer| %>
      <tr>
        <td><%= i %></td>
        <td><%= offer.title %></td>
        <td><%= offer.description %></td>
        <% if current_user&.is_admin %>
          <td><%= offer.requests.select(:user_id).distinct.count %></td>
        <% else %>
          <td>
          <% if user_signed_in? %>
            <%= button_to "Postular", postular_offer_path(offer), method: :post, class: "btn btn-primary btn-sm " %>
          <% else %>
            <%= link_to "Postular", new_user_session_path, class: "btn btn-primary btn-sm ", data: { turbo: false } %>
          <% end %>
        <% end %>
      </tr>
      <% i += 1
      
      #first_admin = User.find_by.(is_admin: true).count
      
       %>
  <% end %>
    </tbody>
  </table>
<% else %> 
  <h1>no hay ofertas de Trabajo</h1>
<%end%>

app/views/offers/new.html.erb
<%= form_with(model: @offer, local: true) do |form| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibieron que esta oferta se guardara:</h2>
      <ul>
        <% @offer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="container forget-password">
    <div class="row">
    <div class="col-md-12 col-md-offset-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="text-center">
            <img src="https://i.ibb.co/rshckyB/car-key.png" alt="car-key" border="0">
            <h2 class="text-center">Nueva oferta Laboral</h2>
            <div class="form-group">
              <%= form.label :title %><br>
              <%= form.text_field :title %>
            </div>
          <div class="field">
          <%= form.label :description %><br>
          <%= form.text_area :description %>
        </div>
        <div class="actions py-2">
          <%= form.submit 'Crear Oferta', class: 'btn btn-secondary' %>
          <%= link_to 'Volver', offers_path, class: 'btn btn-secondary' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/offers/show.html.erb
<h1><%= @offer.title %></h1>
<p><%= @offer.description %></p>


<%= link_to 'Editar', edit_offer_path(@offer), class: 'btn btn-primary' %>
<%= link_to 'Borrar', offer_path(@offer), method: :delete, data: { confirm: '¿Estás seguro de que deseas eliminar esta oferta?' }, class: 'btn btn-danger' %>
<%= link_to 'Volver', offers_path, class: 'btn btn-secondary' %>